project:
  type: website
  output-dir: docs
  resources: 
  - CNAME

website:
  site-url: https://paulogcd.com
  page-footer: "[![](https://img.shields.io/badge/License-CC%20BY--ND%204.0-lightgrey.svg)](https://creativecommons.org/licenses/by-nd/4.0/) Paulo Gugelmo Cavalheiro Dias" 
  navbar:
    title: false
    background: '#BEDDBA'
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Blog"
        href: /blog
      - text: "Contact"
        file: contact.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Paulogcd/paulogcd.github.io
          - text: Report a Bug
            href:  https://github.com/Paulogcd/paulogcd.github.io/issues

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

include-after-body:
  text: |
    <!-- Matomo -->
      <script>
        var _paq = window._paq = window._paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="https://paulogcd.matomo.cloud/";
          _paq.push(['setTrackerUrl', u+'matomo.php']);
          _paq.push(['setSiteId', '1']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.async=true; g.src='https://cdn.matomo.cloud/paulogcd.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
      <!-- End Matomo Code -->