project:
  type: website
  output-dir: docs
  resources: 
  - CNAME

website:
  site-url: https://paulogcd.com
  navbar:
    title: false
    background: '#BEDDBA'
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        href: Projects.qmd
      - text: "Contact"
        file: contact.qmd 
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Paulogcd/paulogcd.github.io
          - text: Report a Bug
            href:  https://github.com/Paulogcd/paulogcd.github.io/issues

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true