project:
  type: website
  output-dir: docs
  resources: 
  - CNAME

website:
  site-url: https://paulogcd.com
  page-footer: "[![](https://img.shields.io/badge/License-CC%20BY--ND%204.0-lightgrey.svg)](https://creativecommons.org/licenses/by-nd/4.0/) Paulo Gugelmo Cavalheiro Dias" 
  navbar:
    title: false
    background: '#BEDDBA'
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Blog"
        href: /blog
      - text: "Contact"
        file: contact.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Paulogcd/paulogcd.github.io
          - text: Report a Bug
            href:  https://github.com/Paulogcd/paulogcd.github.io/issues

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true