
---
title: "Paulo Gugelmo Cavalheiro Dias"
about:
  template: jolla
  links:
    - icon: github
      text: Github
      href: https://github.com/Paulogcd 
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/paulo-gugelmo-cavalheiro-dias/
---

Hello! I am currently working as a research assistant at Sciences Po, in Paris.

I hold a Research Master's degree in Economics from Sciences Po, and worked one year in economic consulting at [GIM](https://www.linkedin.com/company/global-impact-metrics/).

My research interests lie primarily in climate and computational economics, and I intend to pursue an academic career in these fields.
This website serves as a platform to present my work, technical skills, and personal projects. New material is added regularly.

I hold a dual Bachelor's degree in Social Sciences and Political Science from Sciences Po and the Freie Universität Berlin, as well as a Bachelor's degree in Economics from the University of Lorraine in Nancy.

You can access my English CV [here](./Resources/CV/CV_en.pdf) & my french one [here](./Resources/CV/CV_fr.pdf).

The "Projects" section showcases a selection of the research and programming projects I have undertaken during my studies and beyond.



