---
title: "My projects"
---

\begin{center}
Here is a list of some projects I began :
\end{center}

- [Replicaion package of Monge-Naranjo et al., 2019, in Julia (finished)](/Replication_Monge_et_al_2019.jl/dev/) : Together with [CHAMBON Lionel](https://lionelchambon.github.io/) and [COMPERAT Etienne](https://ecomperat.github.io), we proceeded to an attempt of translation from Stata to Julia of the replication package of Monge-Naranjo et al., 2019, Alexander, Juan M. Sánchez, and Raül Santaeulàlia-Llopis. “Natural Resources and Global Misallocation.” American Economic Journal: Macroeconomics 11, no. 2 (2019): 79–126, available online here : [https://www.jstor.org/stable/26621311](https://www.jstor.org/stable/26621311).
This was done for the ["Computational Economics" class](https://floswald.github.io/NumericalMethods/), taught during the Fall 2024 Semester by [Florian Oswald](https://floswald.github.io/) at Sciences Po. 
We obtained the grade of 19 over 20 for this work. 

- [Article Review of _The carbon footprint of capital_, by Chancel and Rehm in 2024 (finished)](/TPEE_Presentation) : This is a group presentation done during the fall semester of 2024-2025 for the class "Topics in Public and Environmental Economics". We were asked to present in one hour the working paper of Chancel and Rehm about how to account the Carbon Footprint of Capital.
The latest version of the article is available [here](https://www.dropbox.com/scl/fi/8jsi7pgno80xlhhjsu3zc/CarbonCapital2023ChancelRehm.pdf?rlkey=nu70bve6k1ofmqz2zpttox9gh&).

- [Macroeconomics 3 Group presentation (finished)](/Macroeconomics-3-Presentation) :
This is a group presentation done in the Fall Semester of 2024 for a Macroeconomics 3 class.
We were asked to present in 5-7 minutes some empirical facts of a paper and their possible link with macroeconomic theory about the topic of wealth inequality.
For this presentation, we choose the article of Junia Howell and James R Elliott, _Damages Done: The Longitudinal Impacts of Natural Hazards on Wealth Inequality in the United States_, Social Problems, Volume 66, Issue 3, August 2019, Pages 448–467,
available here : [https://doi.org/10.1093/socpro/spy016](https://doi.org/10.1093/socpro/spy016).

- [Research Portfolio Tutorial (finished)](/portfolio_tutorial) : This is a tutorial aimed at fellow research students to explain how to create and maintain in a quick and efficient way their online portfolio. It is an introduction to Vscode, Git, Github, and uses Quarto and GitHub Pages to generate and publish the content.

- [Macroeconomics Group Presentation about a Behavioral New Keynesian Model (finished)](/Macroeconomics-2-Presentation) : 
This is a group presentation done in the spring semester of 2024 for a Macroeconomics 2 class that consisted in an article review of _A Behavioral New Keynesian Model_, by Xavier Gabaix (2020). We received a grade of 18 over 20 for this presentation.

- [Microeconomics Group project about modelling pollution tax in a Game Theoretical Framework (finished)](/Micro_project) : 
This is a group project done in the spring semester of 2024 for a Microeconomics 2 class that consisted in the use of notions seen in class on a chosen case. We choose to do it on strategic interactions between firms and government in a context of pollution tax. We received a grade of 14 over 20 for this work. 

- [Webgraph : an attempt to create an R package to make graph visualiation with webscrapping easier on R (dead)](/Webgraph) : 
This was a personal project began in the spring semester of 2024, after being introduced how to create an R library in a introductory class of programming. 